-- 1. Expense Categories Table
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Transactions Table
CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    description TEXT NOT NULL,
    transaction_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    remarks TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Automated Report Schedules Table
CREATE TABLE IF NOT EXISTS report_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id TEXT NOT NULL,
    frequency TEXT NOT NULL,
    emails TEXT NOT NULL,
    scheduled_hour INT DEFAULT 9,
    last_sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.report_schedules
ADD CONSTRAINT unique_schedule_combination
UNIQUE (telegram_id, frequency, emails, scheduled_hour);

-- 4. Seed Core Categories required by code matching UX emojis
INSERT INTO categories (category_name) VALUES
('Groceries'), ('Transport'), ('Utilities'), ('Dining'), ('Shopping'), ('Rent'), ('Entertainment'), ('Medical'), ('Other')
ON CONFLICT (category_name) DO NOTHING;

CREATE TABLE IF NOT EXISTS app_users (
    telegram_id TEXT PRIMARY KEY,
    username TEXT,
    role TEXT NOT NULL DEFAULT 'user',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Register your Telegram ID right away to get instant access
INSERT INTO app_users (telegram_id, username, role)
VALUES ('7511999971', 'Aniket', 'admin')
ON CONFLICT (telegram_id) DO NOTHING;

-- 5. High-Performance RPC for /stats and /statistics command
CREATE OR REPLACE FUNCTION get_user_statistics(p_user_id text)
RETURNS TABLE (category_name text, total_spent numeric) AS $$
BEGIN
  RETURN QUERY
  SELECT COALESCE(c.category_name, 'Other')::text, SUM(t.amount)::numeric
  FROM transactions t
  LEFT JOIN categories c ON t.category_id = c.id
  WHERE t.user_id = p_user_id
  GROUP BY c.category_name
  ORDER BY SUM(t.amount) DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;