import os
import io
import csv
import logging
from fastapi import FastAPI, Request, HTTPException, Header
from datetime import datetime, timedelta
from core.database import supabase
from core.utils import get_ist_now
from core.analytics import get_report_data, parse_date_range
from core.emailer import send_report_email

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(title="Enterprise Cron Engine")

CRON_SECRET = os.environ.get("CRON_SECRET")

@app.get("/api/cron")
async def process_scheduled_reports(authorization: str = Header(None)):
    """Evaluates schedules and dispatches emails for the current IST hour."""
    if not CRON_SECRET or authorization != f"Bearer {CRON_SECRET}":
        raise HTTPException(status_code=401, detail="Unauthorized Cron Execution")

    ist_now = get_ist_now()
    current_hour = ist_now.hour
    
    # Fetch active schedules matching current hour
    try:
        response = supabase.table("report_schedules").select("*").eq("scheduled_hour", current_hour).execute()
        schedules = response.data
    except Exception as e:
        logger.error(f"Failed to fetch schedules: {str(e)}")
        raise HTTPException(status_code=500, detail="Database error")

    dispatched = 0
    for sched in schedules:
        freq = sched['frequency']
        
        # Temporal Logic Constraints
        if freq == 'weekly' and ist_now.weekday() != 0: # Only Mondays
            continue
        if freq == 'monthly' and ist_now.day != 1:      # Only 1st of Month
            continue
        if freq == 'yearly' and (ist_now.day != 1 or ist_now.month != 1): # Only Jan 1st
            continue
            
        # Cooldown Check (Prevent duplicate dispatches in the same day)
        if sched.get('last_sent_at'):
            last_sent = datetime.fromisoformat(sched['last_sent_at'])
            if (ist_now - last_sent).days < 1:
                continue

        # Generate Data
        query_map = {'daily': 'yesterday', 'weekly': 'last week', 'monthly': 'last month', 'yearly': 'last year'}
        query_str = query_map.get(freq, 'yesterday')
        
        try:
            start, end, label = parse_date_range(query_str)
            data = get_report_data(sched['telegram_id'], start, end)
            
            if not data:
                continue # Skip emailing if no expenses exist for period
                
            # Zero-Persistence CSV Generation
            mem_file = io.StringIO()
            writer = csv.writer(mem_file)
            writer.writerow(["Date", "Item Description", "Category", "Amount (INR)"])
            
            total = 0.0
            for item in data:
                total += float(item['amount'])
                cat = item['categories']['category_name'] if item.get('categories') else "Other"
                dt_obj = datetime.fromisoformat(item['transaction_date'])
                writer.writerow([dt_obj.strftime("%Y-%m-%d %H:%M"), item['description'], cat, item['amount']])
                
            mem_file.seek(0)
            csv_bytes = mem_file.getvalue().encode('utf-8')
            filename = f"{freq.capitalize()}_Expense_Report_{label.replace(' ', '_')}.csv"
            
            # Dispatch
            recipients = [email.strip() for email in sched['emails'].split(",")]
            body = f"Hello,\n\nAttached is your {freq} expense report for {label}.\nTotal Spent: ₹{total:,.2f}\n\nAuto-generated by Enterprise Finance Bot."
            
            send_report_email(recipients, f"📊 Your {freq.capitalize()} Financial Report", body, filename, csv_bytes)
            
            # Update last_sent_at safely
            supabase.table("report_schedules").update({"last_sent_at": ist_now.isoformat()}).eq("id", sched['id']).execute()
            dispatched += 1
            
        except Exception as e:
            logger.error(f"Failed to process schedule {sched['id']}: {str(e)}")
            
        finally:
            if 'mem_file' in locals():
                mem_file.close()

    return {"status": "success", "dispatched": dispatched}
